language: scala
scala:
- 2.12.6
script:
- sbt clean test dist
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    - secure: tl42xxvpgooFXq+I5vnrQgp1h4tkbCt8+MOviyi27XS0EbAXsFf39woEBUR54ujYFPq9EX5MD+XGrQIwIdvYXOlqJhuhl4T9aFKNpodxdXnXNNiN5fbjbud9DWTmopuDcVsPu2K8osc1Notjv43PR6qzXFVA4HpdjfJHQtH7IX+QZCtZ+wRvSC3iavF+tpLnD0VTeudgikz16bLSHnuKNtz8Z4wRhJNSuNviwM+wfeem56GqyYAoW7WJDOEKMI3ChZrRkTaCQ7wMV34hOAZ4dvkdehcVKUqOmV6nQW2WyZ1h33YpOrh97uURvOQoJSKf5HVgQqIT0G4VbtwmoxSVd3AYqyWD7stvlQyyWoGGZNiQrL/nFmjOx6Mp5E4T3ZRR6yLawxXWznBzhdchcn8py32pPiVw3Y57tHHWZaD+dNKiGkNMn44OacIbFQZRoSTwzcYEyjXKwYHUHBfb2/08VyWfMyNsaR9tc//i5GmxgHhuWzScWlKju5QdPaAoZ6ZXukIK0nE7SH57qevIqArrpv6lqZwCtBYx0uknSOQsVYWr9jguLfxSEJrOJzDY9rVQggqnHnzHfqTFynj9P8ziHUTjvm76Zq69Y6bl8ny6QvYuSXLyqTrmAxD5F0A1rpuiAx6L8RLKBwPRm1nH17s0K1Ach8bctEJejobL6hoxsbk=
  file_glob: true
  file: target/universal/fish-shop-slack-bot-*-SNAPSHOT.zip
  on:
    tags: true
    repo: jakub-tucek/fish-shop-slack-bot
